if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

if(NOT DEFINED PYTHON_MODULE_FILE)
    set(PYTHON_MODULE_FILE "unknown")
endif()

if(NOT DEFINED PYBIND11_INCLUDE_DIRS)
    set(PYBIND11_INCLUDE_DIRS "unknown")
endif()

string(REPLACE ";" "\n" PYBIND11_INCLUDE_DIRS_LINES "${PYBIND11_INCLUDE_DIRS}")

file(WRITE "${OUTPUT_FILE}" "# Auto-generated by CMake for Cython integration support\n")
file(APPEND "${OUTPUT_FILE}" "python_module=${PYTHON_MODULE_FILE}\n")
file(APPEND "${OUTPUT_FILE}" "pybind11_include_dirs:\n${PYBIND11_INCLUDE_DIRS_LINES}\n")
